//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TermProject.HotelSVC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HotelServiceSoap", Namespace="http://tempuri.org/")]
    public partial class HotelService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetHotelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRoomsByHotelOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindRoomsOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindRoomsByHotelOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReserveOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindCustomerOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HotelService() {
            this.Url = global::TermProject.Properties.Settings.Default.TermProject_HotelSVC_HotelService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetHotelsCompletedEventHandler GetHotelsCompleted;
        
        /// <remarks/>
        public event GetRoomsByHotelCompletedEventHandler GetRoomsByHotelCompleted;
        
        /// <remarks/>
        public event FindRoomsCompletedEventHandler FindRoomsCompleted;
        
        /// <remarks/>
        public event FindRoomsByHotelCompletedEventHandler FindRoomsByHotelCompleted;
        
        /// <remarks/>
        public event ReserveCompletedEventHandler ReserveCompleted;
        
        /// <remarks/>
        public event FindCustomerCompletedEventHandler FindCustomerCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHotels", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetHotels(string city, string state) {
            object[] results = this.Invoke("GetHotels", new object[] {
                        city,
                        state});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetHotelsAsync(string city, string state) {
            this.GetHotelsAsync(city, state, null);
        }
        
        /// <remarks/>
        public void GetHotelsAsync(string city, string state, object userState) {
            if ((this.GetHotelsOperationCompleted == null)) {
                this.GetHotelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHotelsOperationCompleted);
            }
            this.InvokeAsync("GetHotels", new object[] {
                        city,
                        state}, this.GetHotelsOperationCompleted, userState);
        }
        
        private void OnGetHotelsOperationCompleted(object arg) {
            if ((this.GetHotelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHotelsCompleted(this, new GetHotelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRoomsByHotel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetRoomsByHotel(string hotelId) {
            object[] results = this.Invoke("GetRoomsByHotel", new object[] {
                        hotelId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetRoomsByHotelAsync(string hotelId) {
            this.GetRoomsByHotelAsync(hotelId, null);
        }
        
        /// <remarks/>
        public void GetRoomsByHotelAsync(string hotelId, object userState) {
            if ((this.GetRoomsByHotelOperationCompleted == null)) {
                this.GetRoomsByHotelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRoomsByHotelOperationCompleted);
            }
            this.InvokeAsync("GetRoomsByHotel", new object[] {
                        hotelId}, this.GetRoomsByHotelOperationCompleted, userState);
        }
        
        private void OnGetRoomsByHotelOperationCompleted(object arg) {
            if ((this.GetRoomsByHotelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRoomsByHotelCompleted(this, new GetRoomsByHotelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindRooms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable FindRooms(Amenities amenities, string city, string state) {
            object[] results = this.Invoke("FindRooms", new object[] {
                        amenities,
                        city,
                        state});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void FindRoomsAsync(Amenities amenities, string city, string state) {
            this.FindRoomsAsync(amenities, city, state, null);
        }
        
        /// <remarks/>
        public void FindRoomsAsync(Amenities amenities, string city, string state, object userState) {
            if ((this.FindRoomsOperationCompleted == null)) {
                this.FindRoomsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindRoomsOperationCompleted);
            }
            this.InvokeAsync("FindRooms", new object[] {
                        amenities,
                        city,
                        state}, this.FindRoomsOperationCompleted, userState);
        }
        
        private void OnFindRoomsOperationCompleted(object arg) {
            if ((this.FindRoomsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindRoomsCompleted(this, new FindRoomsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindRoomsByHotel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable FindRoomsByHotel(string hotelId, Amenities amenities) {
            object[] results = this.Invoke("FindRoomsByHotel", new object[] {
                        hotelId,
                        amenities});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void FindRoomsByHotelAsync(string hotelId, Amenities amenities) {
            this.FindRoomsByHotelAsync(hotelId, amenities, null);
        }
        
        /// <remarks/>
        public void FindRoomsByHotelAsync(string hotelId, Amenities amenities, object userState) {
            if ((this.FindRoomsByHotelOperationCompleted == null)) {
                this.FindRoomsByHotelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindRoomsByHotelOperationCompleted);
            }
            this.InvokeAsync("FindRoomsByHotel", new object[] {
                        hotelId,
                        amenities}, this.FindRoomsByHotelOperationCompleted, userState);
        }
        
        private void OnFindRoomsByHotelOperationCompleted(object arg) {
            if ((this.FindRoomsByHotelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindRoomsByHotelCompleted(this, new FindRoomsByHotelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Reserve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Reserve(string roomId, string customerId, System.DateTime checkInDate, System.DateTime checkOutDate, string travelSiteId, string travelSitePassword) {
            object[] results = this.Invoke("Reserve", new object[] {
                        roomId,
                        customerId,
                        checkInDate,
                        checkOutDate,
                        travelSiteId,
                        travelSitePassword});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ReserveAsync(string roomId, string customerId, System.DateTime checkInDate, System.DateTime checkOutDate, string travelSiteId, string travelSitePassword) {
            this.ReserveAsync(roomId, customerId, checkInDate, checkOutDate, travelSiteId, travelSitePassword, null);
        }
        
        /// <remarks/>
        public void ReserveAsync(string roomId, string customerId, System.DateTime checkInDate, System.DateTime checkOutDate, string travelSiteId, string travelSitePassword, object userState) {
            if ((this.ReserveOperationCompleted == null)) {
                this.ReserveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReserveOperationCompleted);
            }
            this.InvokeAsync("Reserve", new object[] {
                        roomId,
                        customerId,
                        checkInDate,
                        checkOutDate,
                        travelSiteId,
                        travelSitePassword}, this.ReserveOperationCompleted, userState);
        }
        
        private void OnReserveOperationCompleted(object arg) {
            if ((this.ReserveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReserveCompleted(this, new ReserveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Customer FindCustomer(string customerId, string travelSiteId, string travelSitePassword) {
            object[] results = this.Invoke("FindCustomer", new object[] {
                        customerId,
                        travelSiteId,
                        travelSitePassword});
            return ((Customer)(results[0]));
        }
        
        /// <remarks/>
        public void FindCustomerAsync(string customerId, string travelSiteId, string travelSitePassword) {
            this.FindCustomerAsync(customerId, travelSiteId, travelSitePassword, null);
        }
        
        /// <remarks/>
        public void FindCustomerAsync(string customerId, string travelSiteId, string travelSitePassword, object userState) {
            if ((this.FindCustomerOperationCompleted == null)) {
                this.FindCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindCustomerOperationCompleted);
            }
            this.InvokeAsync("FindCustomer", new object[] {
                        customerId,
                        travelSiteId,
                        travelSitePassword}, this.FindCustomerOperationCompleted, userState);
        }
        
        private void OnFindCustomerOperationCompleted(object arg) {
            if ((this.FindCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindCustomerCompleted(this, new FindCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Amenities {
        
        private int idField;
        
        private bool barField;
        
        private bool businessFacilitiesField;
        
        private bool freeBreakfastField;
        
        private bool freeParkingField;
        
        private bool freeWifiField;
        
        private bool gymField;
        
        private bool poolField;
        
        private bool restaurantField;
        
        private bool spaField;
        
        private double starRatingField;
        
        private bool bathtubField;
        
        private bool nonSmokingField;
        
        private bool petFriendlyField;
        
        private int numOfTwinBedsField;
        
        private int numOfQueenBedsField;
        
        private int numOfKingBedsField;
        
        private bool futonField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public bool Bar {
            get {
                return this.barField;
            }
            set {
                this.barField = value;
            }
        }
        
        /// <remarks/>
        public bool BusinessFacilities {
            get {
                return this.businessFacilitiesField;
            }
            set {
                this.businessFacilitiesField = value;
            }
        }
        
        /// <remarks/>
        public bool FreeBreakfast {
            get {
                return this.freeBreakfastField;
            }
            set {
                this.freeBreakfastField = value;
            }
        }
        
        /// <remarks/>
        public bool FreeParking {
            get {
                return this.freeParkingField;
            }
            set {
                this.freeParkingField = value;
            }
        }
        
        /// <remarks/>
        public bool FreeWifi {
            get {
                return this.freeWifiField;
            }
            set {
                this.freeWifiField = value;
            }
        }
        
        /// <remarks/>
        public bool Gym {
            get {
                return this.gymField;
            }
            set {
                this.gymField = value;
            }
        }
        
        /// <remarks/>
        public bool Pool {
            get {
                return this.poolField;
            }
            set {
                this.poolField = value;
            }
        }
        
        /// <remarks/>
        public bool Restaurant {
            get {
                return this.restaurantField;
            }
            set {
                this.restaurantField = value;
            }
        }
        
        /// <remarks/>
        public bool Spa {
            get {
                return this.spaField;
            }
            set {
                this.spaField = value;
            }
        }
        
        /// <remarks/>
        public double StarRating {
            get {
                return this.starRatingField;
            }
            set {
                this.starRatingField = value;
            }
        }
        
        /// <remarks/>
        public bool Bathtub {
            get {
                return this.bathtubField;
            }
            set {
                this.bathtubField = value;
            }
        }
        
        /// <remarks/>
        public bool NonSmoking {
            get {
                return this.nonSmokingField;
            }
            set {
                this.nonSmokingField = value;
            }
        }
        
        /// <remarks/>
        public bool PetFriendly {
            get {
                return this.petFriendlyField;
            }
            set {
                this.petFriendlyField = value;
            }
        }
        
        /// <remarks/>
        public int NumOfTwinBeds {
            get {
                return this.numOfTwinBedsField;
            }
            set {
                this.numOfTwinBedsField = value;
            }
        }
        
        /// <remarks/>
        public int NumOfQueenBeds {
            get {
                return this.numOfQueenBedsField;
            }
            set {
                this.numOfQueenBedsField = value;
            }
        }
        
        /// <remarks/>
        public int NumOfKingBeds {
            get {
                return this.numOfKingBedsField;
            }
            set {
                this.numOfKingBedsField = value;
            }
        }
        
        /// <remarks/>
        public bool Futon {
            get {
                return this.futonField;
            }
            set {
                this.futonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Customer {
        
        private int idField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string genderField;
        
        private System.DateTime dateOfBirthField;
        
        private string addressField;
        
        private string cityField;
        
        private string stateField;
        
        private int zipCodeField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public int ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetHotelsCompletedEventHandler(object sender, GetHotelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHotelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHotelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetRoomsByHotelCompletedEventHandler(object sender, GetRoomsByHotelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRoomsByHotelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRoomsByHotelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void FindRoomsCompletedEventHandler(object sender, FindRoomsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindRoomsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindRoomsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void FindRoomsByHotelCompletedEventHandler(object sender, FindRoomsByHotelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindRoomsByHotelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindRoomsByHotelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ReserveCompletedEventHandler(object sender, ReserveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReserveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReserveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void FindCustomerCompletedEventHandler(object sender, FindCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Customer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Customer)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591